---
title: "Work OD"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  md_document:
    variant: gfm
    preserve_yaml: true
  html_document:
    code_folding: hide
    css: style.css
    number_sections: no
    theme: flatly
    toc: yes
    toc_float: yes
  pdf_document:
    df_print: kable
    number_sections: no
    toc: yes
  word_document:
    toc: yes
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      dpi = 600, fig.width = 9.45, fig.height = 5.91)

# Global thousand separator
# https://stackoverflow.com/questions/18965637/set-global-thousand-separator-on-knitr
knitr::knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark = ",")
})

options(scipen = 999)

```

```{r}
library(tidyverse)
library(networkD3)
library(ggalluvial)
library(plotly)

# https://stackoverflow.com/questions/55702377/ggplot2-doesnt-show-chinese-character-properly-in-rstudio-server-in-docker
library(showtext)

# library(scales)
library(formattable)

library(ggrepel)

```


```{r}
# https://stackoverflow.com/questions/46996501/readrread-csv-issue-chinese-character-becomes-messy-codes
# work_OD = read_csv("data/data-edited/work_OD_clean.csv",
#                   locale = locale(encoding = 'ISO-8859-1'))

work_OD = read_csv("data/data-edited/work_OD_clean.csv")

work_OD_chi = read_csv("data/data-edited/work_OD_clean_chi.csv")

place_name = read_csv("data/data-edited/place_name.csv")
```


```{r, eval=FALSE}
# TODO: check encoding issue
work_OD_2 = read.csv2(file("data/data-edited/work_OD_clean.csv", encoding = "UTF-8"))

stri_encode(work_OD, from="", to = "UTF-8")



for (col in colnames(work_OD)) {
  print(col)
  work_OD[[col]] = stri_encode(work_OD[[col]], from="", to = "UTF-8")
}

Encoding(work_OD$place_of_residence) <- "UTF-8"
```

# Add categorial variables

```{r}
METROPOLITAN_AREAS = c("Central and Western", "Wan Chai", "Eastern", "Southern", "Yau Tsim Mong", "Sham Shui Po", "Kowloon City", "Wong Tai Sin", "Kwun Tong", "Kwai Tsing", "Tsuen Wan", "Kwai Chung New Town", "Tsuen Wan New Town", "Tsing Yi New Town")

work_OD_order = work_OD_chi %>%
  mutate(
    residence_area = case_when(
      place_of_residence %in% c("Central and Western", "Wan Chai", "Eastern", "Southern") ~ "HKI",
      place_of_residence %in% c("Yau Tsim Mong", "Sham Shui Po", "Kowloon City", "Wong Tai Sin", "Kwun Tong") ~ "KL",
      place_of_residence %in% c("Kwai Tsing", "Tsuen Wan", "Tuen Mun", "Yuen Long") ~ "NTW",
      place_of_residence %in% c("North", "Tai Po", "Sha Tin", "Sai Kung") ~ "NTE",
      place_of_residence %in% c("Islands") ~ "I",
    ),
    work_area = case_when(
      place_of_work %in% c("Central and Western", "Wan Chai", "Eastern", "Southern") ~ "HKI",
      place_of_work %in% c("Yau Tsim Mong", "Sham Shui Po", "Kowloon City", "Wong Tai Sin", "Kwun Tong") ~ "KL",
      place_of_work %in% c("Kwai Chung New Town", "Tsuen Wan New Town", "Tsing Yi New Town", "Tuen Mun New Town", "Tin Shui Wai New Town", "Yuen Long New Town") ~ "NTW",
      place_of_work %in% c("Fanling/ Sheung Shui New Town", "Tai Po New Town", "Sha Tin New Town", "Ma On Shan New Town", "Tseung Kwan O New Town") ~ "NTE",
      place_of_work %in% c("North Lantau New Town") ~ "I",
      place_of_work %in% c("Other areas in the New Territories") ~ "NT_Others",
      place_of_work %in% c("No fixed places of work in Hong Kong/ Marine/ Work at home/ Places outside Hong Kong") ~ "Others",
    ),
    residence_district = ifelse(place_of_residence %in% METROPOLITAN_AREAS, "MA", "NT"),
    work_district = ifelse(place_of_work %in% METROPOLITAN_AREAS, "MA", "NT"),
  ) %>%
  mutate(
    travel_dir = paste0(residence_area,  " to ", work_area),
    same_work_area = ifelse(residence_area == work_area, TRUE, FALSE),
    is_cross_ma_nt = ifelse(residence_district != work_district, TRUE, FALSE)
  )

```


```{r}
# Needs to classify origin and dest as different nodes, even the place of work is same as place of residences
# Add an ending space character to differentiate between origin and dest
work_OD_differentiate = work_OD_order %>%
  mutate(place_of_work_e = paste0(place_of_work, " "))

# drop factor levels
origin_list = as.character(unique(work_OD_differentiate$place_of_residence)) 
destination_list = unique(work_OD_differentiate$place_of_work_e)

# Create node ID including all origin and destination nodes
nodes_OD = data.frame(node_name = c(origin_list, destination_list)) %>%
  unique() %>%
  mutate(node_ID = seq.int(nrow(.)) - 1) # Source/Target needs to be zero-indexed for sankeyNetwork.

```

## Refactor district order

```{r}
DISTRICT_ORDER = c("Central and Western", "Wan Chai", "Eastern", "Southern", "Yau Tsim Mong", "Sham Shui Po", "Kowloon City", "Wong Tai Sin", "Kwun Tong", "Kwai Tsing", "Tsuen Wan", "Tuen Mun", "Yuen Long", "North", "Tai Po", "Sha Tin", "Sai Kung", "Islands")

WORKPLACE_ORDER = c("Central and Western", "Wan Chai", "Eastern", "Southern", "Yau Tsim Mong", "Sham Shui Po", "Kowloon City", "Wong Tai Sin", "Kwun Tong", "Kwai Chung New Town", "Tsuen Wan New Town", "Tsing Yi New Town", "Tuen Mun New Town", "Tin Shui Wai New Town", "Yuen Long New Town", "Fanling/ Sheung Shui New Town", "Tai Po New Town", "Sha Tin New Town", "Ma On Shan New Town", "Tseung Kwan O New Town", "North Lantau New Town", "Other areas in the New Territories", "No fixed places of work in Hong Kong/ Marine/ Work at home/ Places outside Hong Kong")

DISTRICT_ORDER_CHI = c("中西區", "灣仔", "東區", "南區", "油尖旺", "深水埗", "九龍城", "黃大仙", "觀塘", "葵青", "荃灣", "屯門", "元朗", "北區", "大埔", "沙田", "西貢", "離島")

WORKPLACE_ORDER_CHI = c("中西區", "灣仔", "東區", "南區", "油尖旺", "深水埗", "九龍城", "黃大仙", "觀塘", "葵涌新市鎮", "荃灣新市鎮", "青衣新市鎮", "屯門新市鎮", "天水圍新市鎮", "元朗新市鎮", "粉嶺／上水新市鎮", "大埔新市鎮", "沙田新市鎮", "馬鞍山新市鎮", "將軍澳新市鎮",  "北大嶼山新市鎮", "新界其他地區", "在香港沒有固定工作地點／水上／於家中工作／香港以外地方")
```

```{r}
work_OD_plot = work_OD_differentiate %>%
  left_join(nodes_OD, by = c("place_of_residence" = "node_name")) %>%
  rename("origin_ID" = "node_ID") %>%
  left_join(nodes_OD, by = c("place_of_work_e" = "node_name")) %>%
  rename("destination_ID" = "node_ID") 

```

```{r}
# Reorder has to be done after join?
work_OD_plot_reorder = work_OD_plot %>% 
  mutate(
    place_of_residence = factor(place_of_residence, DISTRICT_ORDER),
    place_of_work = factor(place_of_work, WORKPLACE_ORDER),
    place_of_residence_chi = factor(place_of_residence_chi, DISTRICT_ORDER_CHI),
    place_of_work_chi = factor(place_of_work_chi, WORKPLACE_ORDER_CHI)
  )

work_OD_plot_reorder_rmspecial = work_OD_plot_reorder %>%
  subset(place_of_work != "No fixed places of work in Hong Kong/ Marine/ Work at home/ Places outside Hong Kong")

work_OD_plot_reorder_KT = work_OD_plot_reorder %>%
  subset(place_of_work == "Kwun Tong")
```

## ggalluvial

Since we are interested in the actual commuting flow from land to land, here we drop the no fixed place categories.



```{r}
OD_work_alluvial = ggplot(work_OD_plot_reorder_rmspecial, aes(y = N_workers, axis1 = place_of_residence, axis2 = place_of_work)) +
  geom_alluvium(aes(fill = residence_area), width = .2, alpha = .4) +
  geom_stratum(width = .2, fill = "#EEEEEE", color = "#FFFFFF") +
  # http://corybrunson.github.io/ggalluvial/reference/stat_stratum.html
  # https://stackoverflow.com/questions/29465941/format-number-in-r-with-both-comma-thousands-separator-and-specified-decimals
  geom_text(stat = "stratum", aes(label = paste0(after_stat(stratum), "\n", after_stat(format(count, big.mark=",")))), size = 2) +
  scale_x_discrete(limits = c("Place of \nResidence", "Place of \nWork"), expand = c(.05, .05), position = "top") +
  scale_fill_brewer(type = "qual", palette = "Set1") +
  theme_void() +
  theme(
    axis.text.x = element_text(size = 12),
    legend.position = "None",
    aspect.ratio = 3/1
  ) +
  labs(
    title = "Flow of commuters",
    subtitle = "Place of residence and work of commuters in Hong Kong",
    caption = "Note: workers with no fixed places of work or \nwork in Marine/at home/in places outside Hong Kong are excluded."
  )

OD_work_alluvial
```

```{r}
ggsave("OD_work_alluvial.svg", width = 150, height = 450, units = "mm")
```

```{r}
work_OD_plot_reorder_rmspecial_KChighlight = work_OD_plot_reorder_rmspecial %>%
  mutate(alluvial_fill = ifelse(place_of_residence == "Kowloon City", "#4DAF4A", "#D3D3D3"))


```

```{r}
OD_work_alluvial_highlightfromKC = ggplot(work_OD_plot_reorder_rmspecial_KChighlight, aes(y = N_workers, axis1 = place_of_residence, axis2 = place_of_work)) +
  geom_alluvium(aes(fill = alluvial_fill), width = .2, alpha = .4) +
  geom_stratum(width = .2, fill = "#EEEEEE", color = "#FFFFFF") +
  # http://corybrunson.github.io/ggalluvial/reference/stat_stratum.html
  # https://stackoverflow.com/questions/29465941/format-number-in-r-with-both-comma-thousands-separator-and-specified-decimals
  geom_text(stat = "stratum", aes(label = paste0(after_stat(stratum), "\n", after_stat(format(count, big.mark=",")))), size = 2) +
  scale_x_discrete(limits = c("Place of \nResidence", "Place of \nWork"), expand = c(.05, .05), position = "top") +
  scale_fill_identity() +
  theme_void() +
  theme(
    axis.text.x = element_text(size = 12),
    legend.position = "None",
    aspect.ratio = 3/1
  ) +
  labs(
    title = "Flow of commuters",
    subtitle = "Place of residence and work of commuters in Hong Kong",
    caption = "Note: workers with no fixed places of work or \nwork in Marine/at home/in places outside Hong Kong are excluded."
  )

OD_work_alluvial_highlightfromKC
```

```{r}
ggsave("OD_work_alluvial_highlightfromKC.svg", width = 150, height = 450, units = "mm")
```


```{r}
showtext_auto()

OD_work_alluvial_chi = ggplot(work_OD_plot_reorder_rmspecial, aes(y = N_workers, axis1 = place_of_residence_chi, axis2 = place_of_work_chi)) +
  geom_alluvium(aes(fill = residence_area), width = .2, alpha = .4) +
  geom_stratum(width = .2, fill = "#EEEEEE", color = "#FFFFFF") +
  # http://corybrunson.github.io/ggalluvial/reference/stat_stratum.html
  # https://stackoverflow.com/questions/29465941/format-number-in-r-with-both-comma-thousands-separator-and-specified-decimals
  geom_text(stat = "stratum", aes(label = paste0(after_stat(stratum), "\n", after_stat(format(count, big.mark=",")))), size = 2) +
  scale_x_discrete(limits = c("居住地區", "工作地區"), expand = c(.05, .05), position = "top") +
  scale_fill_brewer(type = "qual", palette = "Set1") +
  theme_void() +
  theme(
    axis.text.x = element_text(size = 12),
    legend.position = "None",
    aspect.ratio = 3/1
  ) +
  labs(
    title = "我的訴求就是上班",
    subtitle = "香港",
    caption = "此圖表並不包括沒有固定工作地點及於水上／家中／香港以外地方工作的勞動人口"
  )


OD_work_alluvial_chi

showtext_auto(FALSE)
```
```{r}
ggsave("OD_work_alluvial_chi.svg", width = 150, height = 450, units = "mm")
```

## ggalluvial, colour with whether cross-district or not

```{r}
cross_district_summary = work_OD_plot_reorder %>%
  group_by(residence_area, work_area) %>%
  summarise(
    total_N = sum(N_workers)
  )
```

```{r}
cross_travel_type = work_OD_plot_reorder %>%
  mutate(
    journey_type = case_when(
      travel_dir %in% c("HKI to HKI", "KL to KL", "NTW to NTW", "NTE to NTE", "I to I") ~ "Same Area",
      travel_dir %in% c("HKI to KL", "KL to HKI") ~ "HKI/KL",
      travel_dir %in% c("HKI to NTW", "NTW to HKI") ~"HKI/NTW",
      travel_dir %in% c("HKI to NTE", "NTE to HKI") ~ "HKI/NTE",
      travel_dir %in% c("HKI to I", "I to HKI") ~ "HKI/I",
      travel_dir %in% c("KL to NTW", "NTW to KL") ~ "KL/NTW",
      travel_dir %in% c("KL to NTE", "NTE to KL") ~ "KL/NTE",
      travel_dir %in% c("KL to I", "I to KL") ~ "KL/I",
      travel_dir %in% c("NTW to NTE", "NTE to NTW") ~ "NTW/NTE",
      travel_dir %in% c("NTW to I", "I to NTW") ~ "NTW/I",
      travel_dir %in% c("NTE to I", "I to NTE") ~ "NTE/I",
      travel_dir %in% c("HKI to NT_Others", "KL to NT_Others", "NTW to NT_Others", "NTE to NT_Others", "I to NT_Others") ~ "to_NT_Others",
      travel_dir %in% c("HKI to Others", "KL to Others", "NTW to Others", "NTE to Others", "I to Others") ~ "to_Others"
    )
  ) %>%
  # Combine NTW and I
  mutate(
    journey_type_sim = case_when(
      travel_dir %in% c("HKI to HKI", "KL to KL", "NTW to NTW", "NTE to NTE", "I to I", "NTW to I", "I to NTW") ~ "Same Area",
      travel_dir %in% c("HKI to KL", "KL to HKI") ~ "HKI/KL",
      travel_dir %in% c("HKI to NTW", "NTW to HKI", "HKI to I", "I to HKI") ~ "HKI/NTW",
      travel_dir %in% c("HKI to NTE", "NTE to HKI") ~ "HKI/NTE",
      travel_dir %in% c("KL to NTW", "NTW to KL", "KL to I", "I to KL") ~ "KL/NTW",
      travel_dir %in% c("KL to NTE", "NTE to KL") ~ "KL/NTE",
      travel_dir %in% c("NTW to NTE", "NTE to NTW", "NTE to I", "I to NTE") ~ "NTW/NTE",
      travel_dir %in% c("HKI to NT_Others", "KL to NT_Others", "NTW to NT_Others", "NTE to NT_Others", "I to NT_Others") ~ "to_NT_Others",
      travel_dir %in% c("HKI to Others", "KL to Others", "NTW to Others", "NTE to Others", "I to Others") ~ "to_Others"
    )
  ) %>%
  # HKI, KL, NT, Others
  mutate(
    journey_type_mostsim = case_when(
      travel_dir %in% c("HKI to HKI", "KL to KL", "NTW to NTW", "NTE to NTE", "I to I", "NTW to I", "I to NTW", "NTW to NTE", "NTE to NTW", "NTE to I", "I to NTE", "NTW to NT_Others", "NTE to NT_Others", "I to NT_Others") ~ "Same Area",
      travel_dir %in% c("HKI to KL", "KL to HKI") ~ "HKI/KL",
      travel_dir %in% c("HKI to NTW", "NTW to HKI", "HKI to I", "I to HKI", "HKI to NTE", "NTE to HKI", "HKI to NT_Others") ~ "HKI/NT",
      travel_dir %in% c("KL to NTW", "NTW to KL", "KL to I", "I to KL", "KL to NTE", "NTE to KL", "KL to NT_Others") ~ "KL/NT",
      travel_dir %in% c("HKI to Others", "KL to Others", "NTW to Others", "NTE to Others", "I to Others") ~ "to_Others"
    )
  )

```

```{r}
cross_travel_type_rmspecial = cross_travel_type %>%
  subset(place_of_work != "No fixed places of work in Hong Kong/ Marine/ Work at home/ Places outside Hong Kong")
```


```{r}
cross_travel_type_rmspecial %>%
  group_by(is_cross_ma_nt) %>%
  summarise(
    total_N = sum(N_workers)
  )
```



```{r}
JOURNEY_TYPE_COLOURS_1 = c("Same Area" = "#4daf4a", "HKI/KL" = "#377eb8", "HKI/NT" = "#ff7f00", "KL/NT" = "#984ea3")
JOURNEY_TYPE_COLOURS_2 = c("Same Area" = "#66c2a5", "HKI/KL" = "#8da0cb", "HKI/NT" = "#e78ac3", "KL/NT" = "#fc8d62")

OD_work_alluvial_travelcolour = ggplot(cross_travel_type_rmspecial, aes(y = N_workers, axis1 = place_of_residence, axis2 = place_of_work)) +
  geom_alluvium(aes(fill = journey_type_mostsim), width = .2, alpha = .4) +
  geom_stratum(width = .2, fill = "#EEEEEE", color = "#FFFFFF") +
  # http://corybrunson.github.io/ggalluvial/reference/stat_stratum.html
  # https://stackoverflow.com/questions/29465941/format-number-in-r-with-both-comma-thousands-separator-and-specified-decimals
  geom_text(stat = "stratum", aes(label = paste0(after_stat(stratum), "\n", after_stat(format(count, big.mark=",")))), size = 2) +
  scale_x_discrete(limits = c("Place of \nResidence", "Place of \nWork"), expand = c(.05, .05), position = "top") +
  scale_fill_manual(values = JOURNEY_TYPE_COLOURS_1, aesthetics = c("colour", "fill")) +
  # scale_fill_brewer(type = "qual", palette = "Set1") +
  theme_void() +
  theme(
    axis.text.x = element_text(size = 12),
    legend.position = "None",
    aspect.ratio = 3/1
  ) +
  labs(
    title = "Flow of commuters",
    subtitle = "Place of residence and work of commuters in Hong Kong",
    caption = "Note: workers with no fixed places of work or \nwork in Marine/at home/in places outside Hong Kong are excluded."
  )

OD_work_alluvial_travelcolour
```

```{r}
ggsave("OD_work_alluvial_travelcolour.png", width = 150, height = 450, units = "mm")
```

```{r}
MA_NT_PALETTE = c("FALSE" = "#377eb8", "TRUE" = "#e25a61")

OD_work_alluvial_travelcolour_mant = ggplot(cross_travel_type_rmspecial, aes(y = N_workers, axis1 = place_of_residence, axis2 = place_of_work)) +
  geom_alluvium(aes(fill = is_cross_ma_nt), width = .2, alpha = .4) +
  geom_stratum(width = .2, fill = "#EEEEEE", color = "#FFFFFF") +
  # http://corybrunson.github.io/ggalluvial/reference/stat_stratum.html
  # https://stackoverflow.com/questions/29465941/format-number-in-r-with-both-comma-thousands-separator-and-specified-decimals
  geom_text(stat = "stratum", aes(label = paste0(after_stat(stratum), "\n", after_stat(format(count, big.mark=",")))), size = 2) +
  scale_x_discrete(limits = c("Place of \nResidence", "Place of \nWork"), expand = c(.05, .05), position = "top") +
  scale_fill_manual(values = MA_NT_PALETTE, aesthetics = c("colour", "fill")) +
  # scale_fill_brewer(type = "qual", palette = "Set1") +
  # draw elements outside the plot panel
  # https://stackoverflow.com/questions/50201928/avoid-ggplot2-to-partially-cut-axis-text
  coord_cartesian(clip = 'off') +
  theme_void() +
  theme(
    axis.text.x = element_text(size = 12),
    legend.position = "None",
    aspect.ratio = 3/1
  ) +
  labs(
    title = "Flow of commuters",
    subtitle = "Place of residence and work of commuters in Hong Kong",
    caption = "Note: workers with no fixed places of work or \nwork in Marine/at home/in places outside Hong Kong are excluded."
  )

OD_work_alluvial_travelcolour_mant
```

```{r}
ggsave("OD_work_alluvial_travelcolour_mant.svg", width = 150, height = 450, units = "mm")

```


### Test with highlight effect 

```{r, fig.width=5, fig.height=10}

# manual gghighlight
dataset_simlabel_selected_allu <- dataset_simlabel %>%
  # simulate choosing origins in HKI and all destinations
  mutate(
    journey_type_colour_highlight = ifelse((origin_ID %in% c(0,1,2,3) & destination_ID %in% seq(18, 39)), journey_type_colour, "#cccccc33"),
    ) %>%
  mutate(
    # put highlighted (selected) rows to the top and draw the non-highlighted grey flows first
    journey_type_colour_highlight = factor(journey_type_colour_highlight, levels = c("#4daf4a66", "#377eb866", "#ff7f0066", "#984ea366", "#cccccc33"))
  )

OD_work_alluvial_travelcolour <- 
  ggplot(dataset_simlabel_selected_allu, aes(y = N_workers, axis1 = place_of_residence, axis2 = place_of_work_sim, fill = journey_type_colour_highlight)) +
  geom_alluvium(aes(fill = journey_type_colour_highlight), width = .2, alpha = 1) +
  geom_stratum(width = .2, fill = "#EEEEEE", color = "#FFFFFF") +
  # http://corybrunson.github.io/ggalluvial/reference/stat_stratum.html
  # https://stackoverflow.com/questions/29465941/format-number-in-r-with-both-comma-thousands-separator-and-specified-decimals
  geom_text(stat = "stratum",
            aes(label = paste0(after_stat(stratum),
                               # if count too small (i.e. short stratum height), keep district and count in one single line
                               ifelse(after_stat(count) < 5e4, " - ", "\n"),
                               # count with thousand separators
                               after_stat(format(count, big.mark = ",")))),
            size = 2.25) +
  scale_x_discrete(limits = c("Place of \nResidence", "Place of \nWork"), expand = c(.05, .05), position = "top") +
  # scale_fill_manual(values = MA_NT_PALETTE, aesthetics = c("colour", "fill")) +
  scale_fill_identity() +
  # scale_fill_brewer(type = "qual", palette = "Set1") +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 18),
    plot.caption = element_text(size = 8, vjust = 30),
    # vjust to move x-axis title lower
    axis.text.x = element_text(size = 12, vjust = -15),
    legend.position = "None",
    aspect.ratio = 2/1
  ) +
  labs(
    title = "Flow of commuters",
    subtitle = "Place of residence and work of commuters in Hong Kong",
    caption = "Note: workers with no fixed places of work or \nwork in Marine/at home/in places outside Hong Kong are excluded."
  )

OD_work_alluvial_travelcolour
```


## Heatmap

```{r}
WORKPLACE_ORDER_SIM = c("Central and Western", "Wan Chai", "Eastern", "Southern", "Yau Tsim Mong", "Sham Shui Po", "Kowloon City", "Wong Tai Sin", "Kwun Tong", "Kwai Chung NT", "Tsuen Wan NT", "Tsing Yi NT", "Tuen Mun NT", "Tin Shui Wai NT", "Yuen Long NT", "Fanling/ Sheung Shui NT", "Tai Po NT", "Sha Tin NT", "Ma On Shan NT", "Tseung Kwan O NT", "North Lantau NT", "Others")

cross_travel_type_rmspecial_simlabel = cross_travel_type_rmspecial %>%
  mutate(
    place_of_work_sim = ifelse(place_of_work == "Other areas in the New Territories", "Others", str_replace(place_of_work, "New Town", "NT"))
  ) %>%
  mutate(
    place_of_work_sim = factor(place_of_work_sim, WORKPLACE_ORDER_SIM)
  )
```


```{r}
od_workers_plot = ggplot(cross_travel_type_rmspecial_simlabel, aes(x = place_of_work_sim, y = fct_rev(place_of_residence), fill = N_workers)) +
  geom_tile(color = "#EEEEEE", size = 1) +
  geom_vline(xintercept = c(4.5, 9.5), color = "#ffffff") +
  geom_hline(yintercept = c(9.5, 14.5), color = "#ffffff") +
  scale_fill_viridis_c(option = "A", direction = -1, trans = "log") +
  scale_x_discrete(position = "top") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = -1, hjust = 0),
    aspect.ratio = 18/22
  ) +
  labs(
    y = "Place of residence",
    x = "Place of work",
    title = "The OD of workers"
  )
  
od_workers_plot
```

```{r}
place_of_work_district_details = 
tribble(
  ~place_of_work, ~place_of_work_district,
  "Central and Western", "Central and Western",
  "Wan Chai", "Wan Chai",
  "Eastern", "Eastern",
  "Southern", "Southern",
  "Yau Tsim Mong", "Yau Tsim Mong",
  "Sham Shui Po", "Sham Shui Po",
  "Kowloon City", "Kowloon City",
  "Wong Tai Sin", "Wong Tai Sin",
  "Kwun Tong", "Kwun Tong",
  "Tseung Kwan O New Town", "Sai Kung",
  "Tsuen Wan New Town", "Tsuen Wan",
  "Tuen Mun New Town", "Tuen Mun",
  "Yuen Long New Town", "Yuen Long",
  "Tin Shui Wai New Town", "Yuen Long",
  "Fanling/ Sheung Shui New Town", "North",
  "Tai Po New Town", "Tai Po",
  "Sha Tin New Town", "Sha Tin",
  "Ma On Shan New Town", "Sha Tin",
  "Kwai Chung New Town", "Kwai Tsing",
  "Tsing Yi New Town", "Kwai Tsing",
  "North Lantau New Town", "Islands",
  "Other areas in the New Territories", "Others"
)


```


```{r}

cross_travel_type_rmspecial_simlabel_rmsame = cross_travel_type_rmspecial_simlabel %>%
  left_join(place_of_work_district_details, by = "place_of_work") %>%
  mutate(place_of_resdience_chr = as.character(place_of_residence)) %>%
  mutate(same_district = place_of_resdience_chr == place_of_work_district) %>%
  dplyr::filter(!same_district)
  

od_workers_plot_rmsame = ggplot(cross_travel_type_rmspecial_simlabel_rmsame,
                         aes(x = place_of_work_sim, y = fct_rev(place_of_residence), fill = N_workers)) +
  geom_tile(color = "#EEEEEE", size = 1) +
  geom_vline(xintercept = c(4.5, 9.5), color = "#ffffff") +
  geom_hline(yintercept = c(9.5, 14.5), color = "#ffffff") +
  scale_fill_viridis_c(option = "A", direction = -1, trans = "log") +
  scale_x_discrete(position = "top") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = -1, hjust = 0),
    aspect.ratio = 18/22
  ) +
  labs(
    y = "Place of residence",
    x = "Place of work",
    title = "The OD of workers"
  )
  
od_workers_plot_rmsame
# ggsave("od_workers_plot_rmsame.pdf", dpi = 300)
```

```{r}
NT_AREA = c("NTE", "NTW", "I", "NT_Others")

cross_travel_type_rmspecial_3areas = 
  cross_travel_type_rmspecial_simlabel %>% 
  mutate(
    residence_area_sim = ifelse(residence_area %in% NT_AREA, "NT", residence_area),
    work_area_sim = ifelse(work_area %in% NT_AREA, "NT", work_area)
    ) %>%
  group_by(residence_area_sim, work_area_sim) %>%
  summarise(N_workers = sum(N_workers))

cross_travel_type_rmspecial_5areas = 
  cross_travel_type_rmspecial_simlabel %>% 
  group_by(residence_area, work_area) %>%
  summarise(N_workers = sum(N_workers))
```

```{r}
od_workers_plot_3areas = ggplot(cross_travel_type_rmspecial_5areas,
                         aes(x = work_area, y = fct_rev(residence_area), fill = N_workers)) +
  geom_tile(color = "#EEEEEE", size = 1) +
  geom_text(aes(label = N_workers, color = ifelse(N_workers > 1e5, "#FFFFFF", "#222222"))) +
  scale_fill_viridis_c(option = "A", direction = -1, trans = "log") +
  scale_x_discrete(position = "top") +
  scale_color_identity() +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = -1, hjust = 0),
    aspect.ratio = 18/22
  ) +
  labs(
    y = "Place of residence",
    x = "Place of work",
    title = "The OD of workers"
  )
  
od_workers_plot_3areas
```


```{r}
od_workers_plotly = ggplot(cross_travel_type_rmspecial_simlabel, 
                           aes(x = place_of_work_sim,
                               y = fct_rev(place_of_residence),
                               text = paste0("Place of Residence: ", place_of_residence, "\n", "Place of Work: ", place_of_work_sim, "\n", "Number of Workers: ", formattable::comma(N_workers, digits = 0)),
                               fill = N_workers)
                           ) +
  geom_tile(color = "#EEEEEE", size = 1) +
  geom_vline(xintercept = c(4.5, 9.5), color = "#ffffff") +
  geom_hline(yintercept = c(9.5, 14.5), color = "#ffffff") +
  scale_fill_viridis_c(option = "A", direction = -1, trans = "log") +
  scale_x_discrete(position = "top") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = -1, hjust = 0),
    aspect.ratio = 18/22
  ) +
  labs(
    y = "Place of residence",
    x = "Place of work",
    title = "The OD of workers"
  )

# workaround for transformed colour scale
# https://stackoverflow.com/questions/54107531/ggplotly-mouse-values-while-using-a-log-transformed-color-scale

ggplotly(od_workers_plotly, tooltip = c("text"), height = 540, width = 660)
```

## OD Matrix

```{r}
od_matrix = cross_travel_type_rmspecial_simlabel %>%
  dplyr::select(place_of_residence, place_of_work_sim, N_workers) %>%
  pivot_wider(names_from = place_of_work_sim, values_from = N_workers)
```


## rayshader test

```{r}
plot_gg(od_workers_plot, width = 15, height = 5)

render_snapshot()
```


## Sankey Network

```{r}
nodes_OD_KT = nodes_OD %>% subset(node_ID <= 17 | node_ID == 26) %>%
  dplyr::select(node_name) %>%
  as.data.frame()

work_OD_plot_reorder_KT_char = work_OD_plot_reorder_KT %>%
  mutate(place_of_residence_e = as.character(place_of_residence)) %>%
  rename(
    source = place_of_residence_e,
    target = place_of_work_e,
    value = N_workers,
    IDsource = origin_ID,
    IDtarget = destination_ID
  ) %>%
  dplyr::select(-place_of_residence, place_of_work, residence_area) %>%
  as.data.frame()

```


```{r, eval=FALSE}

# Make the Network
sankeyNetwork(Links = work_OD_plot_reorder_KT_char, Nodes = nodes_OD_KT,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "node_name", 
              sinksRight = FALSE)
```


```{r}
nodes_OD_KT[["node_name"]]

work_OD_plot_reorder_KT_char[["IDsource"]]

work_OD_plot_reorder_KT_char[["IDtarget"]]

work_OD_plot_reorder_KT_char[["value"]]
```

```{r}
library(RColorBrewer)
brewer.pal(n = 5, "Set1")
```


```{r}
# add colour code for links
work_OD_plot_reorder_plotly = work_OD_plot_reorder %>%
  mutate(
    link_colour = case_when(
      residence_area == "HKI" ~ "#E41A1C33",
      residence_area == "KL" ~ "#4DAF4A33",
      residence_area == "NTW" ~ "#FF7F0033",
      residence_area == "NTE" ~ "#984EA333",
      residence_area == "I" ~ "#377EB833"
    )
  )

work_OD_plot_reorder_plotly_rmspecial = work_OD_plot_reorder_plotly %>%
  subset(place_of_work != "No fixed places of work in Hong Kong/ Marine/ Work at home/ Places outside Hong Kong")

work_OD_plot_reorder_plotly_KT = work_OD_plot_reorder_plotly %>%
  subset(place_of_work == "Kwun Tong")

work_OD_plot_reorder_plotly_fromHKI = work_OD_plot_reorder_plotly %>%
  subset(residence_area == "HKI")


```

```{r}
node_y = c(seq(.01, 1, length.out = length(DISTRICT_ORDER)), seq(.01, 1, length.out	= length(WORKPLACE_ORDER)))

# nudged x-axis position for plotly
node_x_nudge = c(seq(0.01, length.out = length(DISTRICT_ORDER), by = 0.01), rev(seq(1, length.out = length(WORKPLACE_ORDER), by = -0.01)))

# nudged x-axis position for plotly
node_x_nudge_2 = c(seq(0.01, length.out = length(DISTRICT_ORDER), by = 0.01), rep(1, length(WORKPLACE_ORDER)))

# nudged x-axis position for plotly
# head() to trim additional values
node_x_nudge_3 = c(head(rep(c(0, .01), ceiling(length(DISTRICT_ORDER)/2)), length(DISTRICT_ORDER)),
                   head(rep(c(1, .99), ceiling(length(WORKPLACE_ORDER)/2)), length(WORKPLACE_ORDER)))


nodes_OD_wposition = nodes_OD %>%
  bind_cols(
    node_y = node_y,
    node_x_nudge = node_x_nudge,
    node_x_nudge_2 = node_x_nudge_2,
    node_x_nudge_3 = node_x_nudge_3) %>%
  mutate(node_x = ifelse(node_ID <= 17, 0, 1))
  
```


```{r}
fig <- plot_ly(
    type = "sankey",
    arrangement = "snap",
    orientation = "h",

    node = list(
      label = nodes_OD_wposition[["node_name"]],
      # x = nodes_OD_wposition[["node_x"]],
      # y = nodes_OD_wposition[["node_y"]],
      color = "#666666",
      pad = 20,
      thickness = 20,
      line = list(
        color = "black",
        width = 0.5
      )
    ),

    link = list(
      source = work_OD_plot_reorder_plotly[["origin_ID"]],
      target = work_OD_plot_reorder_plotly[["destination_ID"]],
      value = work_OD_plot_reorder_plotly[["N_workers"]],
      color = work_OD_plot_reorder_plotly[["link_colour"]]

    )
  )

fig <- fig %>% layout(
    title = "Basic Sankey Diagram",
    font = list(
      size = 10
    )
)

fig
```

```{r}
fig_rmspecial <- plot_ly(
    type = "sankey",
    arrangement = "snap",
    orientation = "h",

    node = list(
      label = nodes_OD_wposition[["node_name"]],
      x = nodes_OD_wposition[["node_x"]],
      y = nodes_OD_wposition[["node_y"]],
      color = "#666666",
      pad = 15,
      thickness = 20,
      line = list(
        color = "black",
        width = 0.5
      )
    ),

    link = list(
      source = work_OD_plot_reorder_plotly_rmspecial[["origin_ID"]],
      target = work_OD_plot_reorder_plotly_rmspecial[["destination_ID"]],
      value = work_OD_plot_reorder_plotly_rmspecial[["N_workers"]],
      color = work_OD_plot_reorder_plotly_rmspecial[["link_colour"]]
      # color = "#00FF00"

    )
  )

fig_rmspecial <- fig_rmspecial %>% layout(
    title = "Basic Sankey Diagram",
    font = list(
      size = 10
    )
)

fig_rmspecial
```

```{r}
nodes_OD_fromHKI = nodes_OD_wposition %>%
  filter(node_ID <=3 | (node_ID >= 18)) %>%
  mutate(node_ID = ifelse(node_ID <= 3 , node_ID, node_ID - 14))

work_OD_plot_reorder_plotly_fromHKI_increID = work_OD_plot_reorder_plotly_fromHKI %>%
  mutate(destination_ID = destination_ID - 14)
```

```{r}

fig_fromHKI <- plot_ly(
    type = "sankey",
    arrangement = "snap",
    orientation = "h",

    node = list(
      label = nodes_OD_fromHKI[["node_name"]],
      x = nodes_OD_fromHKI[["node_x"]],
      y = nodes_OD_fromHKI[["node_y"]],
      color = "#666666",
      pad = 15,
      thickness = 20,
      line = list(
        color = "black",
        width = 0.5
      )
    ),

    link = list(
      source = work_OD_plot_reorder_plotly_fromHKI_increID[["origin_ID"]],
      target = work_OD_plot_reorder_plotly_fromHKI_increID[["destination_ID"]],
      value = work_OD_plot_reorder_plotly_fromHKI_increID[["N_workers"]],
      color = work_OD_plot_reorder_plotly_fromHKI_increID[["link_colour"]]
      # color = "#00FF00"

    )
  )

fig_fromHKI_layout <- fig_fromHKI %>% layout(
    title = "Basic Sankey Diagram",
    font = list(
      size = 10
    )
)

fig_fromHKI_layout
```

```{r}
nodes_OD_fromtoHKI = nodes_OD_wposition %>%
  filter(node_ID <=3 | (node_ID >= 18 & node_ID <= 21))

work_OD_plot_reorder_plotly_fromtoHKI = work_OD_plot_reorder_plotly %>%
  dplyr::filter(residence_area == "HKI" & (destination_ID >= 18 & destination_ID <= 21) )
```


```{r}

fig_fromtoHKI <- plot_ly(
    type = "sankey",
    arrangement = "snap",
    orientation = "h",

    node = list(
      label = nodes_OD_fromtoHKI[["node_ID"]],
      x = nodes_OD_fromtoHKI[["node_x_nudge_3"]],
      y = nodes_OD_fromtoHKI[["node_y"]],
      color = "#666666",
      pad = 15,
      thickness = 20,
      line = list(
        color = "black",
        width = 0.5
      )
    ),

    link = list(
      source = work_OD_plot_reorder_plotly_fromtoHKI[["origin_ID"]],
      target = work_OD_plot_reorder_plotly_fromtoHKI[["destination_ID"]],
      value = work_OD_plot_reorder_plotly_fromtoHKI[["N_workers"]],
      color = work_OD_plot_reorder_plotly_fromtoHKI[["link_colour"]]
      # color = "#00FF00"

    )
  )

fig_fromtoHKI_layout <- fig_fromtoHKI %>% layout(
    title = "Basic Sankey Diagram",
    font = list(
      size = 10
    )
)

fig_fromtoHKI_layout
```


```{r}
library(plotly)
fig <- plot_ly(
  type = "sankey",
  arrangement = "snap",
  node = list(
    label = c("A", "B", "C", "D", "E", "F"),
    x = c(0.2, 0.1, 0.5, 0.7, 0.3, 0.5),
    y = c(0.7, 0.5, 0.2, 0.4, 0.2, 0.3),
    pad = 10), # 10 Pixel
  link = list(
    source = c(0, 0, 1, 2, 5, 4, 3, 5),
    target = c(5, 3, 4, 3, 0, 2, 2, 3),
    value = c(1, 2, 1, 1, 1, 1, 1, 2)))
fig <- fig %>% layout(title = "Sankey with manually positioned node")

fig
```



```{r}
work_OD_plot_reorder_plotly_toKT = work_OD_plot_reorder_plotly %>%
  subset(place_of_work == "Kwun Tong")
```

```{r}

fig_toKT <- plot_ly(
    type = "sankey",
    arrangement = "snap",
    orientation = "h",

    node = list(
      label = nodes_OD_wposition[["node_name"]],
      x = nodes_OD_wposition[["node_x_nudge"]],
      y = nodes_OD_wposition[["node_y"]],
      color = "#666666",
      pad = 15,
      thickness = 20,
      line = list(
        color = "black",
        width = 0.5
      )
    ),

    link = list(
      source = work_OD_plot_reorder_plotly_toKT[["origin_ID"]],
      target = work_OD_plot_reorder_plotly_toKT[["destination_ID"]],
      value = work_OD_plot_reorder_plotly_toKT[["N_workers"]],
      color = work_OD_plot_reorder_plotly_toKT[["link_colour"]]
      # color = "#00FF00"

    )
  )

fig_toKT_layout <- fig_toKT %>% layout(
    title = "Basic Sankey Diagram",
    font = list(
      size = 10
    )
)

fig_toKT_layout
```







```{r}

fig_test <- plot_ly(
    type = "sankey",
    arrangement = "snap",
    orientation = "h",

    node = list(
      label = c("A", "B", "C", "D", "E", "F", "G", "H"),
      x = c(0, 0.01, 0.02, 0, 1, 1, 1, 1),
      y = c(0, .33, .66, 1, 0, .33, .66, 1),
      pad = 10
    ),

    link = list(
      source = c(0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3),
      target = c(4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7),
      value = c(48647, 19244, 42452, 24074, 12938, 21861, 37655, 16625, 8161, 8735, 65803, 8887, 4793, 2503, 8398, 28882)
    )
  )

fig_test <- fig_test %>% layout(
    title = "Basic Sankey Diagram",
    font = list(
      size = 10
    )
)

fig_test
```

